Better to test all/list/etc than the actual query

diff --git a/sa-ssh b/sa-ssh
--- a/sa-ssh
+++ b/sa-ssh
@@ -80,7 +80,7 @@ trap "rm -f '$tmpfile'" EXIT
 
 if knifeq "$query" >"$tmpfile" 2>/dev/null; then
     case "$(grep -c . "$tmpfile")" in
-        0) test "$query" = '*:*' || echo 'Error: no nodes found' 1>&2; exit 1;;
+        0) case "$n" in all|list|sequential|tmux);; *) echo 'Error: no nodes found' 1>&2;; esac; exit 1;;
         1) n="${n:-1}";;
     esac
     if [ -z "$n" ]; then
