Error messages to stderr

diff --git a/sa-ssh b/sa-ssh
--- a/sa-ssh
+++ b/sa-ssh
@@ -61,7 +61,7 @@ trap "rm -f '$tmpfile'" EXIT
 
 if knifeq "$query" >"$tmpfile" 2>/dev/null; then
     case "$(grep -c . "$tmpfile")" in
-        0) echo 'Error: no nodes found'; exit 1;;
+        0) echo 'Error: no nodes found' 1>&2; exit 1;;
         1) n="${n:-1}";;
     esac
     if [ -z "$n" ]; then
@@ -90,11 +90,11 @@ if knifeq "$query" >"$tmpfile" 2>/dev/null; then
             done
             ;;
         *)
-            echo "Error: no node numbered '$n'"
+            echo "Error: no node numbered '$n'" 1>&2
             exit 3
             ;;
     esac
 else
-    echo 'Error: knife query failed'
+    echo 'Error: knife query failed' 1>&2
     exit 1
 fi
